---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: itstarting/cloudfoundry
    tag: "latest"

inputs:
  - name: resource-repo

run:
  path: resource-repo/ci/cf_deployment.sh

params:
  API_ENDPOINT:
  USERNAME:
  PASSWORD:
  ORG:
  SPACE:
  HOST: